### ISSUE TITLE
Dialogue Loop Termination/Continuation Bug

### ISSUE THREAD

**Issue by ryachen01** [stanford-oval/genie-toolkit#315]
Termination Failure:

- Goes into an infinite loop on this: Is there anything else I can help you with? no thanks.

- Is there anything else I can help you with? nope. Sorry, I did not understand that. You might need to enable a new skill before I understand that command.

Continuation Failure:

U: "search for jay chou"
A: "I see Jay Chou and Jay Choudhry. Are you interested to hear more about any of them?" (finally!!)
U: "yes, show me information of Jay Chou"
A: "I have found Jay Chou. It is a musician with 75 popularity. Would you like to learn more?" (75 out of 100?)
U: "yes please"
A: "Sorry, I did not understand that"

**Comment by gcampax** [comment]
The termination issues should have been fixed in #309.

The continuation issue seems to be an accuracy problem, where the "learn_more" dialogue act is not identified correctly. We should annotate that dialogue, add it to the eval set, and then analyze the failure with different models, as with all other accuracy problems.

**Comment by gcampax** [comment]
I'm going to add some more yes/no phrases to the exact matcher through #491, and that should solve this issue reliably.
