### ISSUE TITLE
Street address of some restaurants are not included in agent responses

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/genie-toolkit#514]
Agent replies to commands about some restaurants (but not all) are missing the street address.

Full log:
[log.txt](https://github.com/stanford-oval/thingpedia-common-devices/files/6071033/log.txt)

**Comment by gcampax** [comment]
Ugh, this is an annoying one. The root cause is https://github.com/stanford-oval/thingtalk/pull/318, which causes us to normalize locations incorrectly. Pulling in a new ThingTalk should fix the issue here (and I'll add more tests here too), but we might need to retrain as well because the normalized contexts might change slightly.

**Comment by gcampax** [comment]
This is should be fixed now thanks to the new version of ThingTalk. The fix will percolate to almond-cloud and almond-server soon. Please reopen if you still experience this.
